### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [secure-software-engineering/achilles-benchmark-depscanners#15]
@anddann What would be the license of your tool and data?
Thanks !

**Comment by anddann** [comment]
Thanks for raising that question, I'm currently updating the README.md and link it to the published paper https://ieeexplore.ieee.org/document/9506931/

The license will be MIT, LGPL, or GPL. I'll do the changes in the following week.

**Comment by pombredanne** [comment]
@anddann Thanks. Any free or open source is fine by me.  I am working towards build a vulnerabiltydb and scanner at https://github.com/nexb/vulnerablecode and I would be interested to bench it alright!

**Comment by pombredanne** [comment]
I see you push an LGPL... that's great. Thank you for this!

**Comment by anddann** [comment]
Sounds interesting. If you want just contact me. I've also uploaded statistics about the benchmark.
